{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*?template charset=utf8?*}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="{$site.http_equiv.Content-language|wash}" lang="{$site.http_equiv.Content-language|wash}">

<head>
{ezscript_load( ezini( 'JavaScriptSettings', 'JavaScriptList', 'design.ini' ) )}

{ezcss_load( array( 'core.css',
                    'debug.css',
                    'pagelayout.css',
                    'content.css',                    
                    'websitetoolbar.css',
                    ezini( 'StylesheetSettings', 'CSSFileList', 'design.ini' ) ), 'all' ) }
<link rel="stylesheet" type="text/css" href={"stylesheets/print.css"|ezdesign} />
<style type="text/css" media="print">
    .no-print{ldelim} display:none;{rdelim}
</style>
{include uri="design:page_head.tpl" enable_print=false()}
</head>

<body class="no-js">
<script type="text/javascript">{literal}
//<![CDATA[
(function(){var c = document.body.className;
c = c.replace(/no-js/, 'js');
document.body.className = c;
})();
//]]>{/literal}
</script>

<div id="page">
<h1><a href={"/"|ezurl} title="{ezini('SiteSettings','SiteName')}">{ezini('SiteSettings','SiteName')}</a></h1>
{def $uri = $module_result.uri|explode( '/layout/set/print' )|implode('')|query_string()}
<p id="printuri"><a href="{concat( 'http://', ezsys('hostname'), $uri)}"><span class="no-print">Torna alla visualizzazione normale <br /></span> {concat( 'http://', ezsys('hostname'), $uri)}</a></p>

{include uri="design:page_mainarea.tpl"}
</div>

<!--DEBUG_REPORT-->

</body>
</html>
